### ISSUE TITLE
Does BaGetter Supports NuGet v2 APIs or not?

### ISSUE THREAD

**Issue by mou404** [bagetter/BaGetter#203]
### Describe the bug
When I update from NuGet.Server. to BaGetter, an exception of  Net Connection will occur in the environment of Visual Studio 2013.
Is there an option to downgrade BaGetter to NuGet v2? Thank you for your reply

**Comment by Regenhardt** [comment]
Hi, BaGetter does not support NuGet v2, this has been an open request since early BaGet (https://github.com/loic-sharma/BaGet/issues/43) but was never actually implemented for similar reasons as nuget.org switched to v3. 

Visual Studio 2013 is however long out of support, I suggest to upgrade to VS2022, as the community edition is free and uses nuget v3 api.
